import ollama
import json
import re

def llm_reason_verdict(all_evidence: dict) -> dict:
    """
    Called at the fusion stage in app-ai.py.
    Passes full raw forensic evidence to phi3:mini, which reasons over it
    and produces a structured JSON verdict with per-category risk scores.
    Falls back to simple averaging if Ollama is unavailable or output is malformed.
    """
    prompt = f"""You are a senior Cyber Forensic AI Analyst. You have received raw forensic evidence from multiple analysis modules.
Your job is to reason over this evidence and produce a precise risk assessment.

RAW FORENSIC EVIDENCE:
{json.dumps(all_evidence, indent=2, default=str)}

Based on this evidence, output ONLY a valid JSON object with the following keys (no extra text, no markdown fences):
{{
  "threat_score": <integer 0-100, risk of malware/hidden payload>,
  "ai_generated_score": <integer 0-100, likelihood this was fully AI-generated>,
  "manipulation_score": <integer 0-100, likelihood of tampering/deepfake/splicing>,
  "final_score": <integer 0-100, overall combined risk>,
  "confidence": <"High", "Medium", or "Low">,
  "key_findings": [<list of up to 5 most critical finding strings>],
  "verdict": <"High", "Medium", or "Low">
}}

Rules:
- Base scores ONLY on the evidence provided, not assumptions.
- If a module was not analyzed, do not penalize its score.
- final_score should reflect the worst-case risk across all categories, not a simple average.
- Output ONLY the JSON object. No explanation text outside the JSON.
"""

    fallback = _compute_fallback(all_evidence)

    try:
        response = ollama.generate(model='phi3:mini', prompt=prompt, options={'temperature': 0.0})
        raw = response.get('response', '')

        # Extract JSON from the response
        json_match = re.search(r'\{.*\}', raw, re.DOTALL)
        if json_match:
            verdict = json.loads(json_match.group())
            required = ['threat_score', 'ai_generated_score', 'manipulation_score', 'final_score', 'verdict']
            if all(k in verdict for k in required):
                return verdict

        return fallback
    except Exception:
        return fallback


def _compute_fallback(all_evidence: dict) -> dict:
    """
    Simple averaging fallback if Ollama is unavailable or returns malformed JSON.
    """
    scores = []
    for modality, data in all_evidence.items():
        if isinstance(data, dict) and 'score' in data:
            scores.append(data['score'])

    final = int(sum(scores) / len(scores)) if scores else 0
    verdict = 'High' if final >= 60 else 'Medium' if final >= 30 else 'Low'
    return {
        'threat_score': final,
        'ai_generated_score': final,
        'manipulation_score': final,
        'final_score': final,
        'confidence': 'Low',
        'key_findings': ['LLM unavailable — heuristic fallback scores used'],
        'verdict': verdict
    }


def generate_ai_explanation(verdict_json: dict, all_evidence: dict) -> str:
    """
    Generates the 3-stage narrative report using phi3:mini,
    based on the LLM's own reasoning verdict + the raw evidence.
    """
    prompt = f"""You are a professional Cyber Forensic Investigator AI writing an official investigation report.
You have already produced the following risk verdict:

VERDICT:
{json.dumps(verdict_json, indent=2, default=str)}

SUPPORTING EVIDENCE:
{json.dumps(all_evidence, indent=2, default=str)}

Write a concise, professional 3-stage forensic report using EXACTLY these markdown headings:

### Stage 1: Threat Assessment
(Assess malware, steganography, and hidden payload risks based on the threat_score and evidence.)

### Stage 2: AI-Generation Assessment
(Assess whether the media was fully generated by AI based on ai_generated_score and evidence indicators like missing EXIF, synthetic audio patterns, etc.)

### Stage 3: Deepfake & Manipulation Assessment
(Assess tampering, splicing, or deepfake indicators based on manipulation_score and evidence.)

### FINAL VERDICT
(Summarize the overall risk level, confidence, and key findings in 2-3 sentences.)

Be factual. Do not invent findings not supported by the evidence. Keep each stage to 3-5 sentences.
"""

    try:
        response = ollama.generate(model='phi3:mini', prompt=prompt, options={'temperature': 0.1})
        if response and 'response' in response:
            return response['response']
        return "Failed to parse AI explanation response."
    except Exception as e:
        findings = '\n'.join(f'- {f}' for f in verdict_json.get('key_findings', []))
        return f"""### Stage 1: Threat Assessment
Threat risk score: {verdict_json.get('threat_score', 'N/A')}%. Analysis based on heuristic scanning.

### Stage 2: AI-Generation Assessment
AI-generation likelihood score: {verdict_json.get('ai_generated_score', 'N/A')}%. Based on metadata and signal analysis.

### Stage 3: Deepfake & Manipulation Assessment
Manipulation risk score: {verdict_json.get('manipulation_score', 'N/A')}%. Based on error level and acoustic analysis.

### FINAL VERDICT
Overall risk is **{verdict_json.get('verdict', 'Unknown')}** with a combined score of {verdict_json.get('final_score', 'N/A')}%.
Confidence: {verdict_json.get('confidence', 'Low')}.

Key Findings:
{findings}

(AI Engine Error: {str(e)} — Ensure Ollama is running with `ollama run phi3:mini`)"""
